# Generated by Django 5.2 on 2025-05-03 13:41

import django.db.models.deletion
import racing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=96, unique=True)),
                ('last_name', models.CharField(max_length=96)),
                ('dob', models.DateField(validators=[racing.models.validate_dob])),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('location', models.CharField(max_length=256)),
                ('logo', models.ImageField(upload_to='team_logos/', validators=[racing.models.validate_image_size])),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_track_name', models.CharField(max_length=256)),
                ('track_location', models.CharField(max_length=100)),
                ('race_date', models.DateField(validators=[racing.models.validate_future_date])),
                ('registration_closure_date', models.DateField(blank=True, null=True, validators=[racing.models.validate_past_date])),
                ('registered_drivers', models.ManyToManyField(blank=True, related_name='registered_races', to='racing.driver')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='racing.team'),
        ),
    ]
