# Generated by Django 5.2 on 2025-05-07 07:04

import racing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='drivers',
            field=models.ManyToManyField(related_name='drivers', to='racing.driver'),
        ),
        migrations.AlterField(
            model_name='race',
            name='registration_closure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(upload_to='logos/', validators=[racing.models.validate_image_size]),
        ),
    ]
