# Generated by Django 5.2 on 2025-05-07 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0002_team_drivers_alter_race_registration_closure_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='registered_drivers',
        ),
        migrations.RemoveField(
            model_name='team',
            name='drivers',
        ),
        migrations.AddField(
            model_name='driver',
            name='registered_races',
            field=models.ManyToManyField(blank=True, related_name='registered_drivers', to='racing.race'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='racing.team'),
        ),
    ]
