# Generated by Django 5.2 on 2025-05-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0003_remove_race_registered_drivers_remove_team_drivers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='registered_races',
        ),
        migrations.AddField(
            model_name='race',
            name='registered_drivers',
            field=models.ManyToManyField(blank=True, related_name='registered_races', to='racing.driver'),
        ),
    ]
