# Generated by Django 5.2 on 2025-05-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0004_remove_driver_registered_races_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='first_name',
            field=models.CharField(max_length=96),
        ),
        migrations.AlterField(
            model_name='race',
            name='registered_drivers',
            field=models.ManyToManyField(blank=True, null=True, related_name='registered_races', to='racing.driver'),
        ),
    ]
